### ISSUE TITLE
Some Packages Fail

### ISSUE THREAD

**Issue by scopatz** [regro/conda-metachannel#10]
With a somewhat ridiculously long URL, conda fails to update:

```
scopatz@artemis ~ $ time -p conda update --all 
Solving environment: failed

CondaHTTPError: HTTP 500 CONNECTION FAILED for url <http://35.232.222.82/conda-forge/_license,absl-py,alabaster,alsa-lib,anaconda-client,appdirs,argcomplete,asn1crypto,astor,asttokens,async_generator,atk,atomicwrites,attrs,audioread,autoconf,automake,automat,awscli,babel,backcall,backports,backports.functools_lru_cache,backports.os,backports.shutil_get_terminal_size,backports.weakref,bcolz,beautifulsoup4,bibtexparser,binstar,bitarray,bkcharts,black,blas,bleach,blinker,blosc,blz,bokeh,boost,boost-cpp,boto,boto3,botocore,bz2file,bzip2,c-ares,ca-certificates,cached-property,cairo,cerberus,certifi,cffi,chardet,chrpath,clangdev,click,cloog,cloud_sptheme,cloudpickle,clyent,cmake,coincbc,colorama,conda,conda-build,conda-build-all,conda-env,conda-forge-pinning,conda-smithy,conda-verify,configobj,constantly,contextvars,cryptography,cryptography-vectors,cudatoolkit,curl,cycler,cyclus-build-deps,cython,cytoolz,dask,dask-core,datashape,dbus,decorator,defusedxml,distributed,django,django-extensions,django-haystack,django-widget-tweaks,djangorestframework,docker-compose,docker-py,docker-pycreds,dockerpty,docopt,docutils,drf-haystack,dynd-python,embree,entrypoints,et_xmlfile,eventlet,expat,fastcache,ffmpeg,filelock,flake8,flake8-import-order,flake8-polyfill,flask,flask-socketio,fontconfig,freetype,funcsigs,future,gast,gcc,gdk-pixbuf,gensim,gettext,ghostscript,git-lfs,gitdb,gitdb2,github3.py,gitpython,glib,glibmm,glob2,gmp,gmpy2,gnutls,gobject-introspection,google-cloud-sdk,graphite2,graphviz,greenlet,grpcio,gst-plugins-base,gstreamer,gtk2,gunicorn,h11,h2,h5py,harfbuzz,hdf5,heapdict,hpack,html5lib,hypercorn,hyperframe,hyperlink,icu,idna,imageio,imagesize,immutables,importlib_metadata,incremental,intel-openmp,ipykernel,ipython,ipython_genutils,isl,isodate,itsdangerous,itypes,jbig,jdcal,jedi,jinja2,jmespath,joblib,jpeg,jsoncpp,jsonschema,jupyter_client,jupyter_core,jwcrypto,keras,keras-applications,keras-preprocessing,kiwisolver,krb5,kubernetes,lapack,latexcodec,lazyasd,libarchive,libassuan,libcurl,libdynd,libedit,libffi,libflac,libgcc,libgcc-ng,libgcrypt,libgfortran,libgfortran-ng,libgpg-error,libgpuarray,libiconv,libidn11,libksba,liblief,libogg,libopenblas,libpng,libprotobuf,librosa,libsigcpp,libsndfile,libsodium,libssh2,libstdcxx-ng,libtiff,libtool,libuuid,libuv,libvorbis,libxcb,libxml2,libxmlpp,libxslt,llvm-meta,llvmdev,llvmlite,locket,lxml,lz4,lz4-c,lzo,m4,make,mako,markdown,markupsafe,matplotlib,matplotlib-base,mccabe,memory_profiler,mistune,mkl,mkl-rt,mock,more-itertools,mpc,mpfr,mpi,mpich,mpmath,msgpack-python,msrest,multipledispatch,nbconvert,nbformat,ncurses,ndg-httpsclient,nettle,networkx,nltk,nodejs,nose,notebook,npth,ntbtls,nuitka,numba,numexpr,numpy,numpy-base,numpydoc,oauthlib,odo,olefile,openblas,openpyxl,openssl,oset,outcome,packaging,pandas,pandoc,pandocfilters,pango,parso,partd,patchelf,path.py,patsy,pbr,pcre,pep8,pep8-naming,perl,pexpect,pickleshare,pillow,pip,pixman,pkg-config,pkginfo,pluggy,ply,portaudio,pprintpp,prettytable,profimp,prometheus_client,prompt_toolkit,protobuf,psutil,pthread-stubs,ptyprocess,pv,py,py-lief,pyasn1,pyasn1-modules,pybtex,pybtex-docutils,pycodestyle,pycosat,pycparser,pycrypto,pycurl,pyflakes,pygithub,pygments,pygpu,pyhamcrest,pyjwt,pyopenssl,pyparsing,pyqt,pyrsistent,pysocks,pysoundfile,pystan,pytables,pytest,pytest-django,pytest-django-haystack,pytest-tornado,python,python-coreapi,python-coreschema,python-crfsuite,python-dateutil,python-engineio,python-graphviz,python-libarchive-c,python-socketio,python-sounddevice,python3-openid,pytoml,pytz,pywavelets,pyyaml,pyzmq,qt,qtpy,readline,redis,redis-py,requests,requests-oauthlib,resampy,rhash,rope,rsa,ruamel.yaml,ruamel_yaml,ruby,s3fs,s3transfer,scikit-image,scikit-learn,scipy,send2trash,service_identity,setuptools,sigcpp,simplegeneric,simplejson,sip,six,smart_open,smmap,smmap2,sniffio,snowballstemmer,social-auth-app-django,social-auth-core,sockjs-tornado,sortedcontainers,sparse,sphinx,sphinx_rtd_theme,sphinxcontrib-bibtex,sphinxcontrib-websupport,sqlalchemy,sqlite,statsmodels,sympy,system,tblib,tensorboard,tensorflow,termcolor,terminado,testpath,texttable,theano,tk,toml,toolchain,toolchain_c_linux-64,toolchain_cxx_linux-64,toolz,tornado,tox,tqdm,traitlets,trio,twisted,twython,typing,typing_extensions,ujson,uncertainties,unyt,uritemplate,uritemplate.py,urllib3,urwid,util-linux,uvloop,virtualenv,vitables,vsts-python-api,wcwidth,webencodings,websocket-client,websockets,werkzeug,wheel,whoosh,wsproto,x264,xlrd,xlsxwriter,xlwt,xorg-kbproto,xorg-libice,xorg-libsm,xorg-libx11,xorg-libxau,xorg-libxdmcp,xorg-libxext,xorg-libxpm,xorg-libxrender,xorg-libxt,xorg-renderproto,xorg-xextproto,xorg-xproto,xz,yaml,yasm,zeromq,zict,zlib,zope.interface,zstd,--max-build-no/noarch/repodata.json>
Elapsed: 00:00.223459

A remote server error occurred when trying to retrieve this URL.

A 500-type error (e.g. 500, 501, 502, 503, etc.) indicates the server failed to
fulfill a valid request.  The problem may be spurious, and will resolve itself if you
try your request again.  If the problem persists, consider notifying the maintainer
of the remote server.


Command exited with non-zero status 1
real 6.23
user 5.66
sys 0.13
```

This is every package I have installed dumped to a URL via the following:

```
$ import json
$ "http://35.232.222.82/conda-forge/" + ",".join([i["name"] for i in json.loads($(conda list --json))]) + ",--max-build-no" 
```

**Comment by scopatz** [comment]
Curling the URL leads to:

```
scopatz@artemis ~ $ curl http://35.232.222.82/conda-forge/_license,absl-py,alabaster,alsa-lib,anaconda-client,appdirs,argcomplete,asn1crypto,astor,asttokens,async_generator,atk,atomicwrites,attrs,audioread,autoconf,automake,automat,awscli,babel,backcall,backports,backports.functools_lru_cache,backports.os,backports.shutil_get_terminal_size,backports.weakref,bcolz,beautifulsoup4,bibtexparser,binstar,bitarray,bkcharts,black,blas,bleach,blinker,blosc,blz,bokeh,boost,boost-cpp,boto,boto3,botocore,bz2file,bzip2,c-ares,ca-certificates,cached-property,cairo,cerberus,certifi,cffi,chardet,chrpath,clangdev,click,cloog,cloud_sptheme,cloudpickle,clyent,cmake,coincbc,colorama,conda,conda-build,conda-build-all,conda-env,conda-forge-pinning,conda-smithy,conda-verify,configobj,constantly,contextvars,cryptography,cryptography-vectors,cudatoolkit,curl,cycler,cyclus-build-deps,cython,cytoolz,dask,dask-core,datashape,dbus,decorator,defusedxml,distributed,django,django-extensions,django-haystack,django-widget-tweaks,djangorestframework,docker-compose,docker-py,docker-pycreds,dockerpty,docopt,docutils,drf-haystack,dynd-python,embree,entrypoints,et_xmlfile,eventlet,expat,fastcache,ffmpeg,filelock,flake8,flake8-import-order,flake8-polyfill,flask,flask-socketio,fontconfig,freetype,funcsigs,future,gast,gcc,gdk-pixbuf,gensim,gettext,ghostscript,git-lfs,gitdb,gitdb2,github3.py,gitpython,glib,glibmm,glob2,gmp,gmpy2,gnutls,gobject-introspection,google-cloud-sdk,graphite2,graphviz,greenlet,grpcio,gst-plugins-base,gstreamer,gtk2,gunicorn,h11,h2,h5py,harfbuzz,hdf5,heapdict,hpack,html5lib,hypercorn,hyperframe,hyperlink,icu,idna,imageio,imagesize,immutables,importlib_metadata,incremental,intel-openmp,ipykernel,ipython,ipython_genutils,isl,isodate,itsdangerous,itypes,jbig,jdcal,jedi,jinja2,jmespath,joblib,jpeg,jsoncpp,jsonschema,jupyter_client,jupyter_core,jwcrypto,keras,keras-applications,keras-preprocessing,kiwisolver,krb5,kubernetes,lapack,latexcodec,lazyasd,libarchive,libassuan,libcurl,libdynd,libedit,libffi,libflac,libgcc,libgcc-ng,libgcrypt,libgfortran,libgfortran-ng,libgpg-error,libgpuarray,libiconv,libidn11,libksba,liblief,libogg,libopenblas,libpng,libprotobuf,librosa,libsigcpp,libsndfile,libsodium,libssh2,libstdcxx-ng,libtiff,libtool,libuuid,libuv,libvorbis,libxcb,libxml2,libxmlpp,libxslt,llvm-meta,llvmdev,llvmlite,locket,lxml,lz4,lz4-c,lzo,m4,make,mako,markdown,markupsafe,matplotlib,matplotlib-base,mccabe,memory_profiler,mistune,mkl,mkl-rt,mock,more-itertools,mpc,mpfr,mpi,mpich,mpmath,msgpack-python,msrest,multipledispatch,nbconvert,nbformat,ncurses,ndg-httpsclient,nettle,networkx,nltk,nodejs,nose,notebook,npth,ntbtls,nuitka,numba,numexpr,numpy,numpy-base,numpydoc,oauthlib,odo,olefile,openblas,openpyxl,openssl,oset,outcome,packaging,pandas,pandoc,pandocfilters,pango,parso,partd,patchelf,path.py,patsy,pbr,pcre,pep8,pep8-naming,perl,pexpect,pickleshare,pillow,pip,pixman,pkg-config,pkginfo,pluggy,ply,portaudio,pprintpp,prettytable,profimp,prometheus_client,prompt_toolkit,protobuf,psutil,pthread-stubs,ptyprocess,pv,py,py-lief,pyasn1,pyasn1-modules,pybtex,pybtex-docutils,pycodestyle,pycosat,pycparser,pycrypto,pycurl,pyflakes,pygithub,pygments,pygpu,pyhamcrest,pyjwt,pyopenssl,pyparsing,pyqt,pyrsistent,pysocks,pysoundfile,pystan,pytables,pytest,pytest-django,pytest-django-haystack,pytest-tornado,python,python-coreapi,python-coreschema,python-crfsuite,python-dateutil,python-engineio,python-graphviz,python-libarchive-c,python-socketio,python-sounddevice,python3-openid,pytoml,pytz,pywavelets,pyyaml,pyzmq,qt,qtpy,readline,redis,redis-py,requests,requests-oauthlib,resampy,rhash,rope,rsa,ruamel.yaml,ruamel_yaml,ruby,s3fs,s3transfer,scikit-image,scikit-learn,scipy,send2trash,service_identity,setuptools,sigcpp,simplegeneric,simplejson,sip,six,smart_open,smmap,smmap2,sniffio,snowballstemmer,social-auth-app-django,social-auth-core,sockjs-tornado,sortedcontainers,sparse,sphinx,sphinx_rtd_theme,sphinxcontrib-bibtex,sphinxcontrib-websupport,sqlalchemy,sqlite,statsmodels,sympy,system,tblib,tensorboard,tensorflow,termcolor,terminado,testpath,texttable,theano,tk,toml,toolchain,toolchain_c_linux-64,toolchain_cxx_linux-64,toolz,tornado,tox,tqdm,traitlets,trio,twisted,twython,typing,typing_extensions,ujson,uncertainties,unyt,uritemplate,uritemplate.py,urllib3,urwid,util-linux,uvloop,virtualenv,vitables,vsts-python-api,wcwidth,webencodings,websocket-client,websockets,werkzeug,wheel,whoosh,wsproto,x264,xlrd,xlsxwriter,xlwt,xorg-kbproto,xorg-libice,xorg-libsm,xorg-libx11,xorg-libxau,xorg-libxdmcp,xorg-libxext,xorg-libxpm,xorg-libxrender,xorg-libxt,xorg-renderproto,xorg-xextproto,xorg-xproto,xz,yaml,yasm,zeromq,zict,zlib,zope.interface,zstd,--max-build-no/noarch/repodata.json

<!doctype html>
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
Server got itself in trouble

```

**Comment by CJ-Wright** [comment]
Is this url too long?
`http://35.232.222.82/conda-forge/pyyaml,xonsh,pip,rever/noarch/repodata.json`

I'm also getting a 500 error
```
<!doctype html>
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
Server got itself in trouble
```

**Comment by scopatz** [comment]
Hmm it actually seems like certain packages cause it to fail

**Comment by scopatz** [comment]
For example, rever fails:

```
conda search --override-channels -c http://35.232.222.82/conda-forge/rever xonsh
```

**Comment by CJ-Wright** [comment]
Does the server give any interesting traceback?

**Comment by scopatz** [comment]
The above where generated with the following:

```
import json 
names = [i["name"] for i in json.loads($(conda list --json --no-pip))] 
broken = []
for name in names: 
    print(name + "...", end="", flush=True) 
    if !(conda search --override-channels -c http://35.232.222.82/conda-forge/@(name),--max-build-no @(name)): 
        print("works!") 
    else: 
        broken.append(name) 
        print("breaks!")
```

Same 500-type error as before

**Comment by CJ-Wright** [comment]
Is it looking at the noarch repodata.json?

**Comment by scopatz** [comment]
It can't be only that.  Some of those packages are platform speficic

**Comment by CJ-Wright** [comment]
Right, but if it is looking at the noarch repodata.json then would it get a 500 error?

**Comment by scopatz** [comment]
Actually in the server logs there are a lot of errors of the form:

```
Traceback (most recent call last):
  File "/opt/env/lib/python3.7/site-packages/networkx/classes/digraph.py", line 822, in predecessors
    return iter(self._pred[n])
KeyError: 'zstd'
```

**Comment by scopatz** [comment]
And here is the other exception that happened durring that one:

```
Traceback (most recent call last):
  File "/opt/env/lib/python3.7/site-packages/quart/app.py", line 1462, in handle_request
    return await self.full_dispatch_request(request_context)
  File "/opt/env/lib/python3.7/site-packages/quart/app.py", line 1484, in full_dispatch_request
    result = await self.handle_user_exception(error)
  File "/opt/env/lib/python3.7/site-packages/quart/app.py", line 911, in handle_user_exception
    raise error
  File "/opt/env/lib/python3.7/site-packages/quart/app.py", line 1482, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/opt/env/lib/python3.7/site-packages/quart/app.py", line 1530, in dispatch_request
    return await handler(**request_.view_args)
  File "app.py", line 69, in artifact
    return await loop.run_in_executor(None, repodata_json, channel, constraints, arch)
  File "/opt/env/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "app.py", line 42, in repodata_json
    ag = fetch_artifact_graph(channel, constraints, arch)
  File "app.py", line 37, in fetch_artifact_graph
    ag = get_artifact_graph(channel, arch, constraints)
  File "/work/graph.py", line 256, in get_artifact_graph
    ArtifactGraph._cache[key] = ArtifactGraph(channel, arch, constraints)
  File "/work/graph.py", line 138, in __init__
    self.constrain_graph(self.raw.graph, self.noarch.graph, self.package_constraints)
  File "/work/graph.py", line 146, in constrain_graph
    nodes = recursive_parents(combined_graph, constraints)
  File "/work/graph.py", line 49, in recursive_parents
    children = list(G.predecessors(n))
  File "/opt/env/lib/python3.7/site-packages/networkx/classes/digraph.py", line 824, in predecessors
    raise NetworkXError("The node %s is not in the digraph." % (n,))
networkx.exception.NetworkXError: The node zstd is not in the digraph.
```

**Comment by scopatz** [comment]
And this is noted in the code: https://github.com/regro/conda-metachannel/blob/master/graph.py#L48

**Comment by scopatz** [comment]
@mariusvniekerk - any ideas?

**Comment by scopatz** [comment]
Now we are down to the following broken:

```
['_license',
 'binstar',
 'blz',
 'cudatoolkit',
 'dynd-python',
 'gcc',
 'intel-openmp',
 'libdynd',
 'liblief',
 'libopenblas',
 'mkl',
 'mkl-rt',
 'numpy-base',
 'py-lief',
 'pycurl',
 'redis',
 'sigcpp',
 'sockjs-tornado',
 'system',
 'util-linux']
```

All of these come from other channels, such as defaults:

```
scopatz@artemis ~ $ for name in broken:  
`·.,¸,.·*¯`·.,¸,.·*     conda list --show-channel-urls @(name) 
`·.,¸,.·*¯`·.,¸,.·*                                                                                                                              
# packages in environment at /home/scopatz/miniconda3:
#
# Name                    Version                   Build  Channel
_license                  1.1                      py36_1    defaults
# packages in environment at /home/scopatz/miniconda3:
#
# Name                    Version                   Build  Channel
binstar                   0.12                          2    defaults
# packages in environment at /home/scopatz/miniconda3:
#
# Name                    Version                   Build  Channel
blz                       removed                       0    defaults
# packages in environment at /home/scopatz/miniconda3:
#
# Name                    Version                   Build  Channel
cudatoolkit               9.2                           0    defaults
# packages in environment at /home/scopatz/miniconda3:
#
# Name                    Version                   Build  Channel
dynd-python               removed                       0    defaults
# packages in environment at /home/scopatz/miniconda3:
#
# Name                    Version                   Build  Channel
gcc                       4.8.5                         7    defaults
libgcc                    7.2.0                h69d50b8_2    http://35.232.222.82/conda-forge/--max-build-no
libgcc-ng                 7.2.0                hdf63c60_3    http://35.232.222.82/conda-forge/--max-build-no
# packages in environment at /home/scopatz/miniconda3:
#
# Name                    Version                   Build  Channel
intel-openmp              2019.1                      144    defaults
# packages in environment at /home/scopatz/miniconda3:
#
# Name                    Version                   Build  Channel
libdynd                   0.7.2                         0    defaults
# packages in environment at /home/scopatz/miniconda3:
#
# Name                    Version                   Build  Channel
liblief                   0.9.0                h1532aa0_0    defaults
# packages in environment at /home/scopatz/miniconda3:
#
# Name                    Version                   Build  Channel
libopenblas               0.2.20               h9ac9557_7    defaults
# packages in environment at /home/scopatz/miniconda3:
#
# Name                    Version                   Build  Channel
mkl                       2019.1                      144    defaults
mkl-rt                    11.1                         p0    defaults
# packages in environment at /home/scopatz/miniconda3:
#
# Name                    Version                   Build  Channel
mkl-rt                    11.1                         p0    defaults
# packages in environment at /home/scopatz/miniconda3:
#
# Name                    Version                   Build  Channel
numpy-base                1.14.3           py36h0ea5e3f_1    defaults
# packages in environment at /home/scopatz/miniconda3:
#
# Name                    Version                   Build  Channel
py-lief                   0.9.0            py36h1532aa0_0    defaults
# packages in environment at /home/scopatz/miniconda3:
#
# Name                    Version                   Build  Channel
pycurl                    7.43.0.2         py36hb7f436b_0    defaults
# packages in environment at /home/scopatz/miniconda3:
#
# Name                    Version                   Build  Channel
redis                     4.0.11               h14c3975_0    defaults
redis-py                  3.0.1                      py_0    http://35.232.222.82/conda-forge/--max-build-no
# packages in environment at /home/scopatz/miniconda3:
#
# Name                    Version                   Build  Channel
libsigcpp                 2.10.0               hfc679d8_1    http://35.232.222.82/conda-forge/--max-build-no
sigcpp                    2.30.0                        0    cyclus
# packages in environment at /home/scopatz/miniconda3:
#
# Name                    Version                   Build  Channel
sockjs-tornado            1.0.6                    py36_0    defaults
# packages in environment at /home/scopatz/miniconda3:
#
# Name                    Version                   Build  Channel
system                    5.8                           2    defaults
# packages in environment at /home/scopatz/miniconda3:
#
# Name                    Version                   Build  Channel
util-linux                2.21                          0    default
```

**Comment by mariusvniekerk** [comment]
we can probably skip these
